# Generated by Django 2.2.6 on 2019-10-22 17:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0007_eventmark_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='eventmark',
            name='judge_name',
        ),
        migrations.AddField(
            model_name='eventmark',
            name='judge',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game_manager.Judge'),
        ),
    ]
