# Generated by Django 2.2.6 on 2019-10-22 17:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0008_auto_20191022_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Samithi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Trans')], default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='participant',
            name='samithi',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game_manager.Samithi'),
        ),
    ]
