# Generated by Django 2.2.6 on 2019-10-23 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0010_auto_20191023_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='district',
        ),
    ]
