# Generated by Django 2.2.6 on 2019-10-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0011_remove_participant_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('Boy', 'Boy'), ('Girl', 'Girl')], default=None, max_length=1),
        ),
    ]
