# Generated by Django 2.2.6 on 2019-10-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0012_auto_20191023_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('Boy', 'Boy'), ('Girl', 'Girl')], default=None, max_length=4),
        ),
    ]
