# Generated by Django 2.2.6 on 2019-10-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0014_auto_20191024_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='min_age_limit',
            field=models.IntegerField(default=0),
        ),
    ]
