# Generated by Django 2.2.6 on 2019-10-24 04:51

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0015_group_min_age_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='max_age_limit',
        ),
        migrations.RemoveField(
            model_name='group',
            name='min_age_limit',
        ),
        migrations.AddField(
            model_name='group',
            name='max_dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='min_dob',
            field=models.DateField(default=datetime.date(2019, 10, 24)),
            preserve_default=False,
        ),
    ]
