# Generated by Django 2.2.6 on 2019-10-24 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0016_auto_20191024_0451'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventmark',
            unique_together={('event_participant', 'event_criteria')},
        ),
    ]
