# Generated by Django 2.2.6 on 2019-10-28 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0020_auto_20191028_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='group',
            new_name='groups',
        ),
    ]
