# Generated by Django 2.2.6 on 2019-11-05 17:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0021_auto_20191028_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='accommodation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='arrival_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 5, 17, 26, 54, 771044)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='arrival_point',
            field=models.CharField(choices=[('Railway Station', 'Railway Station'), ('Old Bus Stand', 'Old Bus Stand'), ('New Bus Stand', 'New Bus Stand')], default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='participant',
            name='arrival_time',
            field=models.CharField(default='00:00', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='departure_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 5, 17, 27, 32, 852562)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='departure_time',
            field=models.CharField(default='00:00', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='destination_point',
            field=models.CharField(choices=[('Railway Station', 'Railway Station'), ('Old Bus Stand', 'Old Bus Stand'), ('New Bus Stand', 'New Bus Stand')], default=None, max_length=50),
        ),
        migrations.CreateModel(
            name='ParticipantsFamily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=4)),
                ('relation', models.CharField(choices=[('Family', 'Family'), ('Guru', 'Guru'), ('DEC', 'DEC'), ('SSSO member', 'SSSO member')], default=None, max_length=100)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_manager.Participant')),
            ],
        ),
    ]
