# Generated by Django 2.2.6 on 2019-11-06 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0022_auto_20191105_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='destination_point',
            new_name='departure_point',
        ),
    ]
