# Generated by Django 2.2.6 on 2019-11-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0024_auto_20191106_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantfamily',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=10),
        ),
    ]
