# Generated by Django 2.2.6 on 2019-11-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0025_auto_20191106_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantfamily',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
